#!/usr/bin/env python3

import subprocess
import os

# Define the executable
EXEC = "./StackAndOverlayHistograms"

# Study name
#STUDYNAME = "AN_v6p2-12_v3"
#STUDYNAME = "AN_v6p2-12"
STUDYNAME = "AN_v6p2-13"
STUDYNAME = "AN_v6p4"
#STUDYNAME = "MakePseudo_v1_v3"

# Run periods and channels to loop over
#RUNPERIODS = ["UL2016PreVFP", "UL2016PostVFP", "UL2017", "UL2018"]
#RUNPERIODS = ["UL2017"]
#RUNPERIODS = ["UL2016PostVFP"]
#RUNPERIODS = ["UL2016PreVFP"]
#RUNPERIODS = ["UL2018"]
RUNPERIODS = ["UL2016PreVFP", "UL2016PostVFP", "UL2017", "UL2018"]
#CHANNELS = ["MuMu"]
CHANNELS = ["MuMu", "MuEl", "ElEl"]

# Category mode: True = merged categories, False = individual samples
#USE_CATEGORY_MODE = False
USE_CATEGORY_MODE = True

# Luminosity text mapping
LUMI_TEXTS = {
    "UL2018":        "UL 2018 59.83 fb^{-1} (13 TeV)",
    "UL2017":        "UL 2017 41.48 fb^{-1} (13 TeV)",
    "UL2016PostVFP": "UL 2016NonAPV 16.67 fb^{-1} (13 TeV)",
    "UL2016PreVFP":  "UL 2016APV 19.65 fb^{-1} (13 TeV)",
}

# Configuration files (static)
COLOR_CONFIG = "ColorConfig.txt"
HIST_CONFIG  = "HistConfig.txt"

# Loop over all combinations
for RUNPERIOD in RUNPERIODS:
    for CHANNEL in CHANNELS:
        print(f"\n{'='*70}")
        print(f"Processing: {STUDYNAME} / {RUNPERIOD} / {CHANNEL}")
        print(f"Mode: {'CATEGORY' if USE_CATEGORY_MODE else 'INDIVIDUAL'}")
        print(f"{'='*70}")

        # Input list file
        INPUT_LIST = f"input/{STUDYNAME}/{RUNPERIOD}/{CHANNEL}/{STUDYNAME}_{RUNPERIOD}_{CHANNEL}.list"
        if not os.path.exists(INPUT_LIST):
            print(f"Warning: Input list not found - {INPUT_LIST}")
            print(f"Skipping.\n")
            continue

        # Scale config — must be pre-generated by Generate_ScaleConfig_From_DYSF.py
        SCALE_CONFIG = f"ScaleConfig/{STUDYNAME}/{RUNPERIOD}/{CHANNEL}/ScaleConfig_{STUDYNAME}_{RUNPERIOD}_{CHANNEL}.txt"
        if not os.path.exists(SCALE_CONFIG):
            print(f"Error: ScaleConfig not found - {SCALE_CONFIG}")
            print(f"Please run Generate_ScaleConfig_From_DYSF.py first.")
            print(f"Skipping.\n")
            continue

        # Output directory
        mode_suffix = "_Category" if USE_CATEGORY_MODE else "_Individual"
        OUTPUT_DIR  = f"{STUDYNAME}_DYEstApplied{mode_suffix}/{RUNPERIOD}/{CHANNEL}"
        os.makedirs(f"Histograms/{OUTPUT_DIR}", exist_ok=True)

        # Luminosity text
        LUMI_TEXT = LUMI_TEXTS.get(RUNPERIOD, f"{RUNPERIOD} 13 TeV")

        # Construct command
        cmd = [
            EXEC,
            INPUT_LIST,
            COLOR_CONFIG,
            SCALE_CONFIG,
            HIST_CONFIG,
            OUTPUT_DIR,
            LUMI_TEXT,
            "1" if USE_CATEGORY_MODE else "0",
        ]

        print("Running command:")
        print(" ".join(cmd))
        print()

        try:
            result = subprocess.run(cmd, check=True, text=True, capture_output=True)
            if result.stdout:
                print(result.stdout)
            print(f"✓ Done: Histograms/{OUTPUT_DIR}\n")

        except subprocess.CalledProcessError as e:
            print(f"✗ Error running analysis:")
            print(e.stderr)
            print(f"Continuing to next combination...\n")
            continue
        except FileNotFoundError:
            print(f"✗ Error: Executable '{EXEC}' not found.")
            print("Make sure the executable exists and has execute permissions.")
            exit(1)

print(f"\n{'='*70}")
print(f"All combinations processed!")
print(f"{'='*70}")
